# Type stubs for the PyO3 Rust bindings

class SecurityParams:
    def __init__(self, rng_seed: int) -> None: ...

class ClientKey: ...
class ServerKey: ...

class Ciphertext:
    def __add__(self, rhs: Ciphertext) -> Ciphertext: ...
    def __sub__(self, rhs: Ciphertext) -> Ciphertext: ...
    def __mul__(self, scalar: int) -> Ciphertext: ...

def keygen(params: SecurityParams) -> tuple[ClientKey, ServerKey]: ...
def encrypt(val: int, key: ClientKey) -> Ciphertext: ...
def decrypt(ct: Ciphertext, key: ClientKey) -> int: ...
def set_server_key(key: ServerKey) -> None: ...
def version() -> str: ...
